version: '2'

volumes:
  nextcloud-db-data:
  nextcloud-data:
  nextcloud-config:
  nextcloud-apps:

services:
  nextcloud-nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    links:
      - nextcloud    

  nextcloud-db:
    image: mariadb
    volumes:
      - nextcloud-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  nextcloud:
    image: wonderfall/nextcloud
    environment:
      - UID=${UID}
      - GID=${GID}
      - UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE}
      - APC_SHM_SIZE=${APC_SHM_SIZE}
      - OPCACHE_MEM_SIZE=${OPCACHE_MEM_SIZE}
      - REDIS_MAX_MEMORY=${REDIS_MAX_MEMORY}
      - CRON_PERIOD=${CRON_PERIOD}
      - TZ=${TZ}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_TYPE=${DB_TYPE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    depends_on:
      - nextcloud-db
    volumes:
      - nextcloud-data:/data
      - nextcloud-config:/config
      - nextcloud-apps:/apps2
